site_name: Jerome's studies
repo_url: https://github.com/jbcodeforce/jbcodeforce.github.io/
nav:
  - Introduction: index.md
  - Kafka Studies: https://jbcodeforce.github.com/kafka-studies
  - Openshift Studies: https://jbcodeforce.github.com/openshift-studies
  - Python Studies: https://jbcodeforce.github.com/python-code
  - Spark Studies: https://jbcodeforce.github.io/spark-studies/
  - Angular Studies: https://jbcodeforce.github.io/angular-sandbox/
  - Machine learning: https://jbcodeforce.github.io/ml-basics/
  - My code templates: code-template.md
  - To work on: toworkon.md

theme: 
  name: material
extra_css: ["extra.css"]
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.smartsymbols
  - pymdownx.superfences