site_name: Jerome Boyer's Personal Site
repo_url: https://github.com/jbcodeforce/jbcodeforce.github.io/
nav:
  - Blogs: index.md
  - About: about.md
  - Skill: skill.md
  - List of contributions: assets.md
  - Knowledge base: 
    - Architecture:
      - Event Driven Architecture: architecture/eda.md
      - Architecture decision: architecture/architectural-decisions.md
      - Disaster recovery: architecture/DR.md
      - AWS: architecture/aws.md
      - GCP: architecture/gcp.md
      - IBM Cloud: architecture/ibmcloud.md
      - Openshift Studies: https://jbcodeforce.github.com/openshift-studies
    - Data:
      - Introduction: data/index.md
      - Data topology: data/data-topology.md 
      - Data integration: data/data-integration.md
      - Data replication: data/data-replication.md 
      - Data partitioning: data/data-partitioning.md 
      - Data catalog - spectrum discover: https://www.ibm.com/cloud/architecture/architectures/spectrum-discover
      - OpenData Hub: architecture/opendatahub.md
    - AI:
      - Machine learning: https://jbcodeforce.github.io/ml-basics/
      - Automation Decision Service: techno/ads.md
    - Programming:
      - Java Studies: 
        - Introduction: java/index.md
        - Microprofile 3.x: java/microprofile.md
        - Rest assured: java/restassured.md
        - Concurrency: java/concurrent.md
        - TestContainer: coding/testcontainer.md
        - Open Liberty: java/openliberty.md
        - Quarkus: java/quarkus.md
        - SpringCloud: java/springcloud.md 
        - Vert.x: java/vertx.md
        - Funqy: java/funqy.md
        - Concurrency : java/concurrent.md
        - MQ challenge: java/mqChallenge.md
        - Java FAQ: java/FAQ.md
        - VScode: java/java-vscode.md
      - Python Studies: https://jbcodeforce.github.io/python-code
      - Vue.js Studies:  https://jbcodeforce.github.io/vuejs-studies/
      - Cloud native content IBM: https://cloudnative101.dev/
      - Git summary: git.md
      - Angular Studies: https://jbcodeforce.github.io/angular-sandbox/
      - My code templates: code-template.md
    - Techno:
      - Apicurio: coding/apicurio.md
      - Atlas: techno/atlas.md
      - Cloud object storage: techno/cos.md
      - Code Engine: techno/code-engine.md
      - Redis: techno/redis.md
      - Database play:  https://jbcodeforce.github.io/db-play/  
      - Flink Studies: https://jbcodeforce.github.io/flink-studies/
      - Kafka Studies: https://jbcodeforce.github.io/kafka-studies
      - KAR: techno/kar.md
      - RedPanda Studies: https://github.com/jbcodeforce/redpanda-studies/
      - Spark Studies: https://jbcodeforce.github.io/spark-studies/
      - VScode: java/java-vscode.md

theme: 
  name: material
  logo: 'images/gear-sp-01.jpg'
  feature:
    tabs: true
  palette:
      primary: 'magenta dark'
  social:
    - type: 'github'
      link: 'https://github.com/jbcodeforce'
    - type: 'twitter'
      link: 'https://twitter.com/agileitarch'
    - type: 'linkedin'
      link: 'https://linkedin.com/in/jeromeboyer'
extra_css: ["extra.css"]
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.smartsymbols
  - pymdownx.superfences