site_name: Jerome Boyer's Personal Site
site_description: Knowledge acquisition personal's notes, blog drafts
repo_url: https://github.com/jbcodeforce/jbcodeforce.github.io/
nav:
  - Blogs: blogs/index.md
  - About: about.md
  - Skill: skill.md
  - List of contributions: assets.md
  - Knowledge base: 
    - Architecture:
      - Event Driven Architecture: architecture/eda.md
      - Architecture decision: architecture/architectural-decisions.md
      - DDD : architecture/ddd.md
      - Disaster recovery: architecture/DR.md
      - GCP: architecture/gcp.md
      - IBM Cloud: architecture/ibmcloud.md
      - Istio: istio/index.md
      - Openshift Studies: https://jbcodeforce.github.io/openshift-studies
    - AWS: 
      - Introduction: aws/index.md
      - Playground: aws/gettingstarted.md
      - Kubernetes services: aws/k8s.md
    - Data:
      - Introduction: data/index.md
      - Data topology: data/data-topology.md 
      - Data integration: data/data-integration.md
      - Data replication: data/data-replication.md 
      - Data partitioning: data/data-partitioning.md 
      - Data catalog - spectrum discover: https://www.ibm.com/cloud/architecture/architectures/spectrum-discover
      - OpenData Hub: architecture/opendatahub.md
    - AI:
      - Machine learning: https://jbcodeforce.github.io/ml-basics/
      - Automation Decision Service: techno/ads.md
    - DevOps:
        - Git summary: coding/git.md
        - GitOps: coding/gitops.md
        - Tekton: coding/tekton.md
        - ArgoCD: coding/argocd.md
    - Programming:
      - Java Studies: 
        - Concurrency: java/concurrent.md
        - Funqy: java/funqy.md
        - Introduction: java/index.md
        - Java FAQ: java/FAQ.md
        - Microprofile 3.x: java/microprofile.md
        - Open Liberty: java/openliberty.md
        - Quarkus: java/quarkus.md
        - Rest assured: java/restassured.md
        - SpringCloud: java/springcloud.md 
        - TestContainer: coding/testcontainer.md 
        - Vert.x: java/vertx.md
        - VScode: java/java-vscode.md
      - Python Studies: https://jbcodeforce.github.io/python-code
      - MQ: architecture/mq.md
      - MQ challenge: java/mqChallenge.md
      - Vue.js Studies:  https://jbcodeforce.github.io/vuejs-studies/
      - Cloud native content IBM: https://cloudnative101.dev/ 
      - Openshift Playground: coding/playground.md
      - Angular Studies: https://jbcodeforce.github.io/angular-sandbox/
      - My code templates: code-template.md
    - Techno:
      - Apicurio: techno/apicurio.md
      - Atlas: techno/atlas.md
      - Automation Decision Service: techno/ads.md
      - Self driving enterprise: techno/bai.md
      - Docker: techno/docker.md
      - Cloud object storage: techno/cos.md
      - Code Engine: techno/code-engine.md
      - Database play:  https://jbcodeforce.github.io/db-play/  
      - Egeria: techno/egeria.md
      - Flink Studies: https://jbcodeforce.github.io/flink-studies/
      - Elastic Search: techno/elasticsrch.md
      - Kafka Studies: https://jbcodeforce.github.io/kafka-studies
      - KAR: techno/kar.md
      - Redis: techno/redis.md 
      - RedPanda Studies: https://github.com/jbcodeforce/redpanda-studies/
      - Spark Studies: https://jbcodeforce.github.io/spark-studies/
      - VScode: java/java-vscode.md

theme: 
  name: material
  logo: images/gear-sp-01.jpg
  feature:
    tabs: true
  palette:
    scheme: default
    primary: 'magenta dark'
  language: en
  social:
    - type: 'github'
      link: 'https://github.com/jbcodeforce'
    - type: 'twitter'
      link: 'https://twitter.com/agileitarch'
    - type: 'linkedin'
      link: 'https://linkedin.com/in/jeromeboyer'
extra_css: ["extra.css"]
plugins:
  - search:
      lang: en
      
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - attr_list
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.tabbed
  - pymdownx.details