site_name: Jerome Boyer's Personal Site
repo_url: https://github.com/jbcodeforce/jbcodeforce.github.io/
nav:
  - Blogs: index.md
  - About: about.md
  - Skill: skill.md
  - List of contributions: assets.md
  - Knowledge base: 
    - Architecture:
      - Event Driven Architecture: architecture/eda.md
      - Architecture decision: architecture/architectural-decisions.md
      - AWS: architecture/aws.md
      - GCP: architecture/gcp.md
      - IBM Cloud: architecture/ibmcloud.md
      - Openshift Studies: https://jbcodeforce.github.com/openshift-studies
      - Data:
        - Data integration: architecture/data-integration.md
        - Data partitioning: architecture/data-partitioning.md 
        - Data topology: architecture/data-topology.md 
        - Data replication: architecture/data-replication.md 
        - Data catalog - spectrum discover: https://www.ibm.com/cloud/architecture/architectures/spectrum-discover
        - OpenData Hub: opendatahub.md
    - Programming:
      - Java Studies: 
        - Introduction: java/index.md
        - Microprofile 3.x: java/microprofile.md
        - Concurrency: java/concurrent.md
        - Open Liberty: java/openliberty.md
        - Quarkus: java/quarkus.md
        - Vert.x: java/vertx.md
        - Funqy: java/funqy.md
        - Concurrency : java/concurrent.md
        - MQ challenge: java/mqChallenge.md
        - Java FAQ: java/FAQ.md
        - VScode: java/java-vscode.md
      - Python Studies: https://jbcodeforce.github.com/python-code
      - Vue.js Studies:  https://jbcodeforce.github.io/vuejs-studies/
      - Machine learning: https://jbcodeforce.github.io/ml-basics/
      - Cloud native content IBM: https://cloudnative101.dev/
      - Apicurio: coding/apicurio.md
      - Git summary: git.md
      - My code templates: code-template.md
    - Techno:
      - Kafka Studies: https://jbcodeforce.github.com/kafka-studies
      - Spark Studies: https://jbcodeforce.github.io/spark-studies/
      - Flink Studies: https://jbcodeforce.github.io/flink-studies/
      - RedPanda Studies: https://jbcodeforce.github.io/redpanda-studies/
      - Database play:  https://jbcodeforce.github.io/db-play/  
      - Angular Studies: https://jbcodeforce.github.io/angular-sandbox/
      - Code Engine: code-engine.md
      - VScode: java-vscode.md

theme: 
  name: material
  logo: 'images/cloud.png'
  feature:
    tabs: true
  palette:
      primary: 'magenta dark'
  social:
    - type: 'github'
      link: 'https://github.com/jbcodeforce'
    - type: 'twitter'
      link: 'https://twitter.com/agileitarch'
    - type: 'linkedin'
      link: 'https://linkedin.com/in/jeromeboyer'
extra_css: ["extra.css"]
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.smartsymbols
  - pymdownx.superfences