site_name: Jerome Boyer's Personal Site
site_description: Knowledge acquisition personal's notes, blog drafts
repo_url: https://github.com/jbcodeforce/jbcodeforce.github.io/
site_url: https://jeromeboyer.net
docs_dir: docs
site_dir: public
edit_uri: edit/master/docs
copyright: Copyright &copy; 2018 - 2024 Jerome Boyer
theme: 
  name: material
  logo: images/logo.drawio.png
  favicon: images/logo-blue.drawio.png
  palette:
    scheme: default
    # primary: blue
  language: en
  features:
      - content.code.annotate
      - content.code.copy
      - content.tooltips
      - search.highlight
      - navigation.instant
      - navigation.instant.progress
      - navigation.tabs
      - navigation.instant
      - navigation.tabs.sticky
      - navigation.tracking
      # - navigation.sections
      # - navigation.expand
      - navigation.footer
      - navigation.tabs.sticky
      - navigation.top
extra:
  social:
    - icon: fontawesome/brands/github
      link: 'https://github.com/jbcodeforce'
    - icon: fontawesome/brands/linkedin
      link: 'https://linkedin.com/in/jeromeboyer'
    - icon: fontawesome/solid/paper-plane
      mailto: jerome@intelligent-automations.com
extra_css: ["extra.css"]
plugins:
  - search:
      lang: en
  - minify:
      minify_html: true
  - mermaid2
markdown_extensions:
  - abbr
  - attr_list
  - md_in_html
  - admonition
  - codehilite
  - footnotes
  - tables
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.tabbed
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.details

  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: 
    - About: about.md
    - Skills: skills.md
    - Blogs: blogs/index.md
    - Leasure: 
      - Astronomy: astronomy/index.md
      - Physic - Newton: astronomy/physic.md
  - Coding:
      - Playground: coding/playground.md
      - Dev & Ops:
        - Agile: coding/agile.md
        - Git summary: coding/git.md
        - GitOps: coding/gitops.md
        - Tekton: coding/tekton.md
        - ArgoCD: coding/argocd.md
        - Finch: coding/finch.md
      - Fun problems:
        - puzzles: fun/puzzles.md
      - Java: 
        - Introduction: java/index.md
        - Java FAQ: java/FAQ.md
        - Concurrency: java/concurrent.md
        - Funqy: java/funqy.md
        - Microprofile 3.x: java/microprofile.md
        - Open Liberty: java/openliberty.md
        - Quarkus: java/quarkus.md
        - Rest assured: java/restassured.md
        - SpringCloud: java/springcloud.md 
        - TestContainer: coding/testcontainer.md 
        - Vert.x: java/vertx.md
        - VScode: java/java-vscode.md
      - Podman: techno/podman.md
      - React.js & next.js: coding/reactjs/index.md
      - istio: coding/istio/index.md
      - Python: https://jbcodeforce.github.io/python-code
      - Knative: coding/knative.md
      - Vue.js Studies:  https://jbcodeforce.github.io/vuejs-studies/
      - Cloud native content IBM: https://cloudnative101.dev/ 
      - Angular: https://jbcodeforce.github.io/angular-sandbox/
      - My code templates: code-template.md
  - Knowledge base: 
    - The SA job: blogs/consultant-job.md
    - Architecture:
      - Conduct System Design: architecture/system-design.md
      - Event Driven Architecture: https://jbcodeforce.github.io/eda-studies
      - TPC/IP summary: architecture/tcpip.md
      - Flow architectures: architecture/flow-architectures.md
      - Streaming processing: architecture/streaming.md
      - Architecture decision: architecture/architectural-decisions.md
      - DDD : https://jbcodef orce.github.io/eda-studies/ddd
      - Disaster recovery: architecture/DR.md
      - Istio: istio/index.md
      - Openshift Studies: https://jbcodeforce.github.io/openshift-studies
    - Methodology: 
      - Design Thinking: methodology/design-thinking/index.md
      - Data intensive: methodology/data-intensive/index.md
      - Event Storming: https://jbcodeforce.github.io/eda-studies/event-storming/
      - Domain driven design: https://jbcodeforce.github.io/eda-studies/ddd/
      - Lean startup: methodology/lean-startup.md
      - Product manager: methodology/pm.md
      - ABRD:
        - Introduction: methodology/abrd/index.md
        - Rule Harvesting: methodology/abrd/harvesting.md
      - Narratives: methodology/narrative.md
    - Data:
      - Introduction: data/index.md
      - Iceberg & others: techno/data/index.md
      - Database play:  https://jbcodeforce.github.io/db-play/  
      - Data topology: data/data-topology.md 
      - Data integration: data/data-integration.md
      - Data replication: data/data-replication.md 
      - Data partitioning: data/data-partitioning.md 
      - Streaming processing: architecture/streaming.md
      - OpenData Hub: architecture/opendatahub.md
      - OLAP: data/olap.md
      - Cassandra: data/cassandra.md
    - AI:
      - Machine learning: https://jbcodeforce.github.io/ML-studies/#machine-learning
      - Deep learning: https://jbcodeforce.github.io/ML-studies/ml/deep-learning/
    
  - Techno:
    - Apicurio: techno/apicurio.md
    - Atlas: techno/atlas.md
    - AWS body of knowledge: https://jbcodeforce.github.io/yarfba
    - Databricks: techno/databricks/index.md
    - Docker: techno/docker.md
    - Drools: techno/decisions/drools.md
    - Podman: techno/podman.md
    - Microcks: techno/microcks.md
    - Minikube: techno/minikube.md
    - WSL2-Ubuntu: techno/wsl2.md
    - Rancher Desktop: techno/rancherdesktop.md
    - Code Engine: techno/code-engine.md 
    - Egeria: techno/egeria.md
    - Prometheus: techno/prometheus.md
    - Flink Studies: https://jbcodeforce.github.io/flink-studies/
    - Elastic Search: techno/elasticsrch.md
    - Kafka Studies: https://jbcodeforce.github.io/kafka-studies
    - KAR: techno/kar.md
    - Redis: techno/redis.md 
    - Red Panda: https://jbcodeforce.github.io/redpanda-studies/
    - Spark Studies: https://jbcodeforce.github.io/spark-studies/
    - VScode: java/java-vscode.md
    - IBM:
      - IBM Cloud: architecture/ibmcloud.md
      - IBM Cloud Satellite: architecture/satellite.md
      - Cloud object storage: techno/cos.md
      - Cloud Pak Automation: 
        - Overview: techno/cp4a/index.md
        - BAI: techno/cp4a/bai.md
        - ODM: techno/cp4a/odm.md
        - Automation Decision Service: techno/cp4a/ads.md
        - Process mining: techno/cp4a/process-mining.md
      - Cloud Pak integration: 
        - Overview: techno/integration/cp4i.md
        - APIC: techno/integration/apic.md
        - EEPM: techno/integration/eepm.md
        - MQ: 
          - Overview: techno/integration/mq.md
          - MQ challenge: java/mqChallenge.md


    