site_name: Jerome's studies
repo_url: https://github.com/jbcodeforce/jbcodeforce.github.io/
nav:
  - Introduction: index.md
  - List of assets: assets.md
  - Java Studies: https://jbcodeforce.github.com/java-studies
  - Kafka Studies: https://jbcodeforce.github.com/kafka-studies
  - Openshift Studies: https://jbcodeforce.github.com/openshift-studies
  - Python Studies: https://jbcodeforce.github.com/python-code
  - Spark Studies: https://jbcodeforce.github.io/spark-studies/
  - Flink Studies: https://jbcodeforce.github.io/flink-studies/
  - Vue.js Studies:  https://jbcodeforce.github.io/vuejs-studies/
  - Database play:  https://jbcodeforce.github.io/db-play/
  - Angular Studies: https://jbcodeforce.github.io/angular-sandbox/
  - Machine learning: https://jbcodeforce.github.io/ml-basics/
  - Code Engine: code-engine.md
  - Cloud native content IBM: https://cloudnative101.dev/
  - AWS: aws.md
  - IBM Cloud: ibmcloud.md
  - My code templates: code-template.md
  - Git summary: git.md
  - To work on: toworkon.md

theme: 
  name: material
  logo: 'images/cloud.png'
  feature:
    tabs: true
  palette:
      primary: 'blue grey'
      primary: 'deep purple'
  social:
    - type: 'github'
      link: 'https://github.com/jbcodeforce'
    - type: 'twitter'
      link: 'https://twitter.com/agileitarch'
    - type: 'linkedin'
      link: 'https://linkedin.com/in/jeromeboyer'
extra_css: ["extra.css"]
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.smartsymbols
  - pymdownx.superfences